<a href="https://colab.research.google.com/github/ErickOlivetto/projeto_modulo_2_bootcamp_datascience/blob/main/Notebooks/limpeza_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
def arruma_df(banco_dados:pd.DataFrame, regioes:dict):
  banco_dados = banco_dados.drop('Total', axis = 1)
  banco_dados = banco_dados.melt('Unidade da Federação')
  banco_dados = banco_dados.rename(columns = {'Unidade da Federação':'uf', 'variable' : 'ano', 'value' : 'valor'})
  banco_dados['regiao'] = banco_dados['uf'].str[0].map(regioes)
  banco_dados = banco_dados.set_index('uf')
  banco_dados['ano'] = banco_dados['ano'].astype('int32')
  banco_dados.index = banco_dados.index.str[3:]
  banco_dados = banco_dados.dropna()
  return banco_dados

In [3]:
url_cobertura_vacinal = 'https://github.com/ErickOlivetto/projeto_modulo_2_bootcamp_datascience/raw/main/Dados/cobertura_vacinal_uf.csv'
url_calculo_cv = 'https://github.com/ErickOlivetto/projeto_modulo_2_bootcamp_datascience/raw/main/Dados/calculo_cv_uf.csv'

In [4]:
dados_cobertura_vacinal = pd.read_csv(url_cobertura_vacinal, sep = ';', skiprows = 3, engine = 'python', skipfooter = 20, decimal = ',', na_values = '...')
dados_cobertura_vacinal

      Unidade da Federação   1994   1995   1996  ...   2017   2018   2019  Total
0              11 Rondônia  42.76  50.80  76.05  ...  80.74  82.45  51.44  79.88
1                  12 Acre  20.53  46.61  36.59  ...  62.18  67.44  45.44  69.26
2              13 Amazonas  20.15  35.82  49.88  ...  65.33  69.82  49.97  69.65
3               14 Roraima  64.06  88.84  89.18  ...  74.26  78.76  48.04  75.68
4                  15 Pará  32.44  40.11  51.26  ...  57.60  57.44  37.53  73.89
5                 16 Amapá    NaN  34.68  44.75  ...  58.66  63.32  44.02  72.88
6             17 Tocantins    NaN    NaN  65.44  ...  81.70  82.32  57.59  78.47
7              21 Maranhão  27.43  35.69  41.05  ...  60.87  64.51  40.05  73.91
8                 22 Piauí  62.22  48.16  46.40  ...  67.25  70.80  44.88  73.15
9                 23 Ceará  49.20  50.06  60.28  ...  73.67  77.37  47.53  75.75
10  24 Rio Grande do Norte  41.34  49.23  56.57  ...  53.69  67.54  38.10  68.77
11              25 Paraíba    NaN  22.82  45.23  ...  66.15  69.43  43.87  72.02
12           26 Pernambuco  33.46  78.01  72.86  ...  65.20  70.43  44.91  75.12
13              27 Alagoas    NaN  28.35  46.58  ...  65.01  70.79  44.26  70.26
14              28 Sergipe    NaN  67.66  67.28  ...  63.49  68.76  46.21  74.36
15                29 Bahia  42.98  28.19  38.02  ...  63.11  63.50  38.68  72.39
16         31 Minas Gerais    NaN    NaN    NaN  ...  80.42  85.42  53.43  78.03
17       32 Espírito Santo  55.22  74.91  75.62  ...  66.35  74.22  48.72  76.09
18       33 Rio de Janeiro    NaN  43.29  36.26  ...  67.04  61.37  25.99  69.70
19            35 São Paulo    NaN  45.01  44.86  ...  67.29  71.52  46.18  71.68
20               41 Paraná    NaN  35.30  51.84  ...  77.66  81.79  58.11  75.08
21       42 Santa Catarina  51.60  55.47  48.53  ...  75.82  82.43  60.59  74.53
22    43 Rio Grande do Sul    NaN  65.25  58.90  ...  72.54  74.94  51.65  70.96
23   50 Mato Grosso do Sul    NaN    NaN  39.02  ...  78.81  83.52  52.21  79.69
24          51 Mato Grosso  31.76  37.67  37.44  ...  74.28  76.70  46.38  76.12
25                52 Goiás  22.37  69.81  66.93  ...  73.25  71.85  47.04  77.66
26     53 Distrito Federal    NaN   0.34  55.99  ...  73.82  73.85  49.58  74.74

[27 rows x 28 columns]

In [5]:
dados_calculo_cv = pd.read_csv(url_calculo_cv, sep = ';', skiprows = 3, engine = 'python', skipfooter = 20, encoding = 'ISO-8859-1', na_values = '-')
dados_calculo_cv

      Unidade da Federação      1994       1995  ...      2018     2019      Total
0              11 Rondônia  150744.0   169930.0  ...    554429   344707   13579585
1                  12 Acre   22658.0    57518.0  ...    266548   183891    6538933
2              13 Amazonas  127265.0   236612.0  ...   1435823   996366   31196446
3               14 Roraima   38382.0    56559.0  ...    237162   146819    4334259
4                  15 Pará  440625.0   552664.0  ...   1994916  1299432   64447319
5                 16 Amapá       NaN    32559.0  ...    241570   165800    6025103
6             17 Tocantins       NaN        NaN  ...    469306   337453   11640134
7              21 Maranhão  395000.0   482285.0  ...   1808791  1123803   56584379
8                 22 Piauí  327096.0   288726.0  ...    813143   520133   24205309
9                 23 Ceará  708696.0   731122.0  ...   2596746  1559778   67305775
10  24 Rio Grande do Norte  192475.0   257873.0  ...    773048   427102   21737039
11              25 Paraíba       NaN   160631.0  ...    974210   608801   27688567
12           26 Pernambuco  527256.0  1191428.0  ...   2410864  1536040   69511165
13              27 Alagoas       NaN   178302.0  ...    926598   584861   24915175
14              28 Sergipe       NaN   237617.0  ...    574293   375131   16167894
15                29 Bahia  994130.0   722003.0  ...   3165767  1933369  104332948
16         31 Minas Gerais       NaN        NaN  ...   5380265  3396051  133030903
17       32 Espírito Santo  256603.0   397685.0  ...   1042704   697564   25874717
18       33 Rio de Janeiro       NaN   906575.0  ...   3678944  1506798  102583485
19            35 São Paulo       NaN  2694310.0  ...  11407247  7249108  277238149
20               41 Paraná       NaN   610367.0  ...   3143311  2226662   74590280
21       42 Santa Catarina  437164.0   529270.0  ...   1933449  1436410   41606715
22    43 Rio Grande do Sul       NaN  1096689.0  ...   2675382  1829584   67951747
23   50 Mato Grosso do Sul       NaN        NaN  ...    900946   569408   19569152
24          51 Mato Grosso  174627.0   196972.0  ...   1053524   657632   23814777
25                52 Goiás  209872.0   590541.0  ...   1764350  1139751   44441261
26     53 Distrito Federal       NaN     1297.0  ...    887622   609503   19195368

[27 rows x 28 columns]

In [6]:
regioes = {'1':'Norte', '2':'Nordeste', '3':'Sudeste', '4':'Sul', '5':'Centro-Oeste'}
dados_cobertura_vacinal = arruma_df(dados_cobertura_vacinal, regioes)
dados_calculo_cv = arruma_df(dados_calculo_cv, regioes)

In [7]:
dados_cobertura_vacinal.to_csv('./dados_cobertura_vacinal.csv')
dados_calculo_cv.to_csv('./dados_calculo_cv.csv')